name: alfred_convert_workflow
description: Convert between different units with Alfred

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  alfred_workflow: ^0.2.8
  autoequal: ^0.5.1
  args: ^2.3.0
  cli_script: ^0.2.6
  collection: ^1.16.0
  decimal: ^2.3.0
  emojis: ^0.9.9
  envied: ^0.2.3
  equatable: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  rational: ^2.2.0
  recase: ^4.1.0
  stash: ^4.3.4
  stash_file: ^4.3.4
  timezone: ^0.9.0
  units_converter: ^2.0.1
  xml: ^6.1.0

dev_dependencies:
  autoequal_gen: ^0.5.1
  build_runner: ^2.1.7
  envied_generator: ^0.2.3
  lints: ^2.0.0
  dart_code_metrics: ^4.8.1
  json_serializable: ^6.1.5
