name: alfred_convert_workflow
description: Convert between different units with Alfred

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.4

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  alfred_workflow: ^0.3.2+1
  autoequal: ^0.5.1
  args: ^2.4.1
  cli_script: ^0.3.1
  collection: ^1.17.2
  decimal: ^2.3.2
  emojis: ^0.9.9
  envied: ^0.3.0+3
  equatable: ^2.0.5
  http: ^0.13.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  path: ^1.8.3
  rational: ^2.2.2
  recase: ^4.1.0
  stash: ^4.5.3
  stash_file: ^4.5.3
  timezone: ^0.9.2
  units_converter: ^2.1.0
  xml: ^6.3.0

dev_dependencies:
  autoequal_gen: ^0.5.1
  build_runner: ^2.4.4
  envied_generator: ^0.3.0+3
  lints: ^2.1.0
  dart_code_metrics: ^5.7.4
  json_serializable: ^6.7.0
