name: alfred_convert_workflow
description: Convert between different units with Alfred

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.5

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  alfred_workflow: ^0.4.0
  autoequal: ^0.5.1
  args: ^2.4.2
  cli_script: ^1.0.0
  collection: ^1.17.2
  decimal: ^2.3.3
  emojis: ^0.9.9
  envied: ^0.3.0+3
  equatable: ^2.0.5
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  path: ^1.8.3
  rational: ^2.2.2
  recase: ^4.1.0
  stash: ^5.0.0
  stash_file: ^5.0.0
  timezone: ^0.9.2
  units_converter: ^2.1.0
  xml: ^6.3.0

dev_dependencies:
  autoequal_gen: ^0.5.1
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  lints: ^2.1.1
  json_serializable: ^6.7.1
